variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

stages:
    - test_build
    - post_build_test
    - deploy

test:
    image: fpco/stack-build:lts-10.3
    stage: test_build
    script:
        - stack setup --system-ghc
        - stack test --system-ghc --coverage --test-arguments "--color always --quickcheck-tests 1000"
        - mkdir -p ./public/coverage
        - cp -r $(stack path --system-ghc --local-hpc-root)/* ./public/coverage
    coverage: '/(\d+)\% expressions used/'
    cache:
        key: test
        paths:
            - .stack
            - .stack-work
    artifacts:
        paths:
            - public/
        expire_in: 1 hour

bench:
    image: fpco/stack-build:lts-10.3
    stage: test_build
    script:
        - stack setup --system-ghc
        - mkdir -p ./public/benchmark
        - stack bench --system-ghc --benchmark-arguments "-o ./public/benchmark/index.html"
    cache:
        key: bench
        paths:
            - .stack
            - .stack-work
    artifacts:
        paths:
            - public/
        expire_in: 1 hour

build-cpp:
    image: fpco/stack-build:lts-10.3
    stage: test_build
    script:
        - stack setup --system-ghc
        - mkdir build
        - stack install htar9-asm:htar9-asm-exe --system-ghc --local-bin-path build
    cache:
        key: build
        paths:
            - .stack
            - .stack-work
    artifacts:
        paths:
            - build/

build-hs:
    image: fpco/stack-build:lts-10.3
    stage: test_build
    script:
        - stack setup --system-ghc
        - mkdir build
        - stack install htar9-asm:htar9-asm-hs-exe --system-ghc --local-bin-path build
    cache:
        key: build
        paths:
            - .stack
            - .stack-work
    artifacts:
        paths:
            - build/

build-isa-pdf:
    image: aergus/latex
    script:
        - cd docs
        - latexmk -lualatex -interaction=nonstopmode isa.tex
        - cd ..
        - mkdir public
        - mv ./docs/isa.pdf ./public
    artifacts:
        paths:
            - public/
        expire_in: 1 hour

pages:
    # stage precedence means previous stage artifacts will be downloaded
    stage: deploy
    script:
        echo "some script to run to appease gitlab CI"
        # TODO: get haddock working on haddocking my code not all but my code
        #- stack haddock htar9-asm --haddock-arguments "--odir=${CI_PROJECT_DIR}/public/docs"
        #- stack ide targets --system-ghc
        #- echo ${CI_COMMIT_REF_SLUG}
    only:
        refs:
            - master
    artifacts:
        paths:
            - public/
