name:                htar9-asm
version:             0.1.0.0
github:              "BorisNikulin/htar9-asm"
license:             MIT
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2018 Boris Nikulin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/BorisNikulin/htar9-asm#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring < 1
- megaparsec >= 6 && < 7
- mtl >= 2 && < 3
- containers < 1
- optparse-applicative < 1
- filepath >= 1 && < 2
- microlens-platform < 1
- vector < 1
- primitive < 1
- void

default-extensions:
- OverloadedStrings

ghc-options:
- -fno-warn-tabs

library:
  source-dirs: src

executables:
  htar9-asm-exe:
    main:                main.cpp
    source-dirs:         src/cpp
    c-sources:
    - src/cpp/interpreter.cpp
    - src/cpp/haskell_facade.cpp
    - src/cpp/ncurses_display.cpp

    ghc-options:
    - -threaded
    - -no-hs-main
    extra-libraries:
      - stdc++
      - ncurses
    dependencies:
    - htar9-asm
  htar9-asm-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htar9-asm

tests:
  htar9-asm-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htar9-asm
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - smallcheck
