name:                htar9-asm
version:             0.1.0.0
github:              "BorisNikulin/htar9-asm"
license:             MIT
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2018 Boris Nikulin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/BorisNikulin/htar9-asm#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring < 1
- megaparsec >= 6 && < 7
- mtl >= 2 && < 3
- containers < 1
- microlens-platform < 1
- void

default-extensions:
- OverloadedStrings

#ghc-options:
#- -fno-warn-tabs

library:
  source-dirs: src

executables:
  htar9-asm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htar9-asm

tests:
  htar9-asm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htar9-asm
